---
name: Pytest Workflow with Allure History

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest pytest-html

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          ALLURE_URL="https://github.com/allure-framework/allure2"
          ALLURE_FILE="allure-2.27.0.tgz"
          wget "$ALLURE_URL/releases/download/2.27.0/$ALLURE_FILE"
          sudo tar -xzf $ALLURE_FILE -C /opt/
          sudo ln -sf /opt/allure-2.27.0/bin/allure /usr/bin/allure

      - name: Get previous Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-history

      - name: Run pytest and copy history
        run: |
          mkdir -p allure-results
          if [ -d "gh-pages-history/history" ]; then
            echo "Copying history from previous run"
            cp -r gh-pages-history/history allure-results/
          fi
          pytest -s --alluredir=allure-results tests/

      - name: Generate Allure Report
        run: |
          if [ -d "gh-pages-history/history" ]; then
            cp -r gh-pages-history/history allure-results/ || true
          fi
          allure generate allure-results --clean -o _site
          mkdir -p _site/history
          if [ -d "allure-results/history" ]; then
            cp -r allure-results/history _site/ || true
          fi
          touch _site/.nojekyll

      - name: Deploy reports to GitHub Pages
        if: ${{ github.actor != 'nektos/act' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
          keep_files: true
          force_orphan: false
