---
name: Pytest Workflow with Allure History

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest pytest-html

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          GOOGLE_KEY="https://dl-ssl.google.com/linux/linux_signing_key.pub"
          wget -q -O - $GOOGLE_KEY | sudo apt-key add -
          CHROME_LIST="/etc/apt/sources.list.d/google-chrome.list"
          CHROME_REPO="deb [arch=amd64] "
          CHROME_REPO="${CHROME_REPO}http://dl.google.com/linux/chrome/deb/"
          CHROME_REPO="${CHROME_REPO} stable main"
          echo $CHROME_REPO | sudo tee $CHROME_LIST
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | \
            awk '{print $3}' | cut -d '.' -f 1)
          echo "Chrome major version: $CHROME_VERSION"

          BASE_URL="https://googlechromelabs.github.io"
          RELEASE_URL="${BASE_URL}/chrome-for-testing"
          CHROMEDRIVER_VERSION=$(curl -s \
            "${RELEASE_URL}/LATEST_RELEASE_${CHROME_VERSION}")
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"

          STORAGE_URL="https://storage.googleapis.com"
          DOWNLOAD_PATH="chrome-for-testing-public"
          DOWNLOAD_URL="${STORAGE_URL}/${DOWNLOAD_PATH}"
          DOWNLOAD_URL="${DOWNLOAD_URL}/${CHROMEDRIVER_VERSION}"
          DOWNLOAD_URL="${DOWNLOAD_URL}/linux64/chromedriver-linux64.zip"

          wget -q "$DOWNLOAD_URL" -O chromedriver.zip
          unzip -q chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          ALLURE_URL="https://github.com/allure-framework/allure2"
          ALLURE_FILE="allure-2.27.0.tgz"
          wget "$ALLURE_URL/releases/download/2.27.0/$ALLURE_FILE"
          sudo tar -xzf $ALLURE_FILE -C /opt/
          sudo ln -sf /opt/allure-2.27.0/bin/allure /usr/bin/allure

      - name: Download previous Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-history

      - name: Run pytest with Allure
        run: |
          mkdir -p allure-results
          if [ -d "gh-pages-history/history" ]; then
            echo "Copying history from previous run"
            cp -r gh-pages-history/history allure-results/
          fi
          pytest -s --alluredir=allure-results tests/

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o _site
          if [ -d "_site/history" ]; then
            echo "History preserved successfully"
          else
            echo "No history found in report"
          fi
          touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
          keep_files: true
          force_orphan: false
